previewsEnabled: true
previewsExpireAfterDays: 3
services:
- type: web
  plan: standard
  previewPlan: starter
  name: express-backend
  env: node
  buildCommand: cd backend && npm ci
  startCommand: cd backend && npm start
  envVars:
  - key: MY_API_KEY
    value: production-api-key
    previewValue: test-api-key
  - key: DB_CONNECTION_STRING
    fromDatabase:
      name: postgres_db
      property: connectionString
  - key: BAR
    sync: false
  - fromGroup: foo
  - fromGroup: foo-preview
- type: web
  name: render-todo
  env: static
  buildCommand: cd frontend && npm install && npm run build
  staticPublishPath: ./frontend/build
  envVars:
  - key: REACT_APP_API_HOST
    fromService:
      type: web
      name: express-backend
      property: host
  - key: SKIP_INSTALL_DEPS
    value: false
databases:
- name: postgres_db
  databaseName: test_db
  user: test_user
  plan: standard
  previewPlan: starter
